### PR TITLE
optsWithGlobals contains merged local and global option values

### PR DESCRIPTION
**Pull request by enisdenjo**

### CODE REVIEW

**Comment by shadowspawn** [comment]
Hmm, the `optsWithGlobals` is unmodified from Commander and hopefully we can do better.

The use of the generic in Commander is to allow the author to supply the "whole" return type, so what you have done is right for use without a custom type but not as intended for when the type is supplied.

I have not checked the syntax yet, but I am imagining a default combination of generic options (globals) and Opts like:
```
optsWithGlobals<T extends OptionValues =  Opts & OptionValues>(): T;
```

i.e. It won't be strongly typed but should know about the local option names.

**Comment by enisdenjo** [comment]
But it's a mess to infer the values of the command. My instinct is that the globals are the generic, and the inferred values are just merged.

Let's say `Globals` is the type containing the globals - how would you write the code so that the method returns the globals and the command specific types (`Opts`)?

**Comment by shadowspawn** [comment]
The existing simple Commander generic could be used like:
```
import { Command }  from '@commander-js/extra-typings';

const program = new Command()
    .option('--global');

const po = program.opts();

program.command('sub')
   .option('--local')
   .action((options, command) => {
        const co = command.opts();
        const combo = command.optsWithGlobals<ReturnType<typeof program['opts']> & ReturnType<typeof command['opts']>>();
   });
```

**Comment by shadowspawn** [comment]
I think with this declaration, the default type would at least know about the local options (for autocompletion et al) and allow specifying arbitrary options as before. A step forward. 

```
  optsWithGlobals<T extends OptionValues = Opts & OptionValues>(): T;
```
Screenshot 2024-10-16 at 18 25 29

**Comment by enisdenjo** [comment]
If you try to pass in the globals, you then lose the local options. This is what I am trying to avoid.

```ts
type Globals { foo: string; };
const opts = command.optsWithGlobals<Globals>();

opts.foo ✅
opts.local ❌
```

Can you fix this code so that it supports `local` too? Of course, without too much mumbo jumbo.

---

The documentation on `optsWithGlobals` clearly states:
> Return an object containing merged local and global option values as key-value pairs.
So, the same way you don't pass the generic of locals in `opts`, you should not pass the generic of locals to `optsWithGlobals`. Intuitively, you want to pass only the generic of globals.

**Comment by shadowspawn** [comment]
I am having a go at automatic strong typing for the globals. See #78.

**Comment by shadowspawn** [comment]
Closing in favour of #78 which adds built-in typing of the global options.

**Pull request closed without merging**
