### PR TITLE
Make generic choices type const

### PR DESCRIPTION
**Pull request by matthyk**
While working on #59 I noticed that since TypeScript 5.0 it is possible to declare generic types as const. This infers the value as const. The advantage of this is that the command type is more strictly typed. For this to work we need PR #59, but I wanted to make these new changes in a separate PR.

```ts
program
  .addOption(new Option('-o, --opt', '').choices(['a', 'b', 'c']))
  .action(function () {
    expectType<Command<[], { opt?: true | 'a' | 'b' | 'c' }>>(this)
  })
```
instead of
```ts
program
  .addOption(new Option('-o, --opt', '').choices(['a', 'b', 'c']))
  .action(function () {
    expectType<Command<[], { opt?: true | string }>>(this)
  })
```

### CODE REVIEW

**Comment by shadowspawn** [comment]
Oh nice. This is independent of #59 and the work-around is actually covered in the README: 

> Use a "const assertion" on the choices to narrow the option type from string

**Comment by shadowspawn** [comment]
Typescript 5 is somewhat "recent" and I think might have to wait for a breaking major update of this package in the future to adopt this, or do more work and support multiple versions: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions

**Comment by shadowspawn** [comment]
DefinitelyTyped has a handy graphic of their 2-year TypeScript testing support: https://github.com/DefinitelyTyped/DefinitelyTyped#support-window

**Comment by matthyk** [comment]
Since one can achieve the same with `as const`, we should stick to the timeline from DefinitelyTyped

**Comment by shadowspawn** [comment]
I am keeping an eye out for Typescript dependencies in other projects.

A new version of typescript-eslint is supporting TypeScript `>=4.7.4`:
- https://typescript-eslint.io/blog/announcing-typescript-eslint-v7#breaking-changes

**Comment by mrazauskas** [comment]
> should have a test that runs against oldest supported TypeScript

@shadowspawn

To draw your attention, [`TSTyche`](https://tstyche.org) is a type testing tool that is able to use specified version of TypeScript: `tstyche --target 4.8,latest`. This simple!

It also has `test()` helper with `.only` and `.skip` modifiers. Also `--watch` mode. And much more.

---

Note that the install size of `tstyche` is only around 220kB. This is because the installed TypeScript is loaded by default.

In contrary `tsd`s install size is 48.0MB. They ship their own copy to TypeScript. (Or maybe even two? Because the install size of the latest version of `typescript` package is 20.9MB.)

**Comment by shadowspawn** [comment]
Thanks @mrazauskas , I had not seen TSTyche.

**Comment by shadowspawn** [comment]
Version 4.9 of TypeScript is about to drop off the DefinitelyTyped tests, and Version 13 of Commander is still in flight so I think we can target the 13.x branch.

There are some branch conflicts showing in the web interface, likely because of the Prettier reformat, and some diffs showing up from the reverted `this` work. Are you up for doing a rebase/cleanup @matthyk ? 

(I don't mind redoing the PR myself if you are not interested, only a few changes and I will add you as co-author.)

**Comment by shadowspawn** [comment]
Closed in favour of #79

Thanks for the tip @matthyk

**Pull request closed without merging**
